### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by TwofivefiveSH** [totalaj/poke-counter#1]
Love the counter, just wanted to see if you'd be able to give it an option to increment two counters with the same input? Perhaps only in the same group? For example if you were counting total encounters over multiple hunts(like safari week or fossil wrek) hile resetting a single counter, another feature that's missing is having a customizable text option, right now I'm just making my own text in Ms paint and importing it as an image but it gets awkward, thanks in advance if possible <3

**Comment by totalaj** [comment]
Added the fix to global hotkeys. I've created a new issue for the other request here: https://github.com/totalaj/poke-counter/issues/2
